dist: trusty
sudo: required
language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
cache: npm
after_success: 'npm run coveralls'

os:
  - linux

jobs:
  include:
    - stage: test
      script: npm run test
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
      if: branch = master AND type != pull_request
